// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyeolisdgjnwjfxrvnyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZW9saXNkZ2pud2pmeHJ2bnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzE2MTIsImV4cCI6MjA2OTU0NzYxMn0.FaX54kFfE_nyNARENuof1toKDRoE_NzlAi31zj8q_us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});